backend:
  name: git-gateway
  branch: dependabot/bundler/addressable-2.8.1  # o master, se usi quello

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"  # ⬅️ Importantissimo per Jekyll

    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }  # 👈 ECCOLO!
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Categorie", name: "categories", widget: "list", default: ["blog"] }
      - { label: "Contenuto", name: "body", widget: "markdown" }
